
varDictionnaries:
  - name: "ReactionCode"
    dictionary: "./misc/ReactionCodesDict.yaml"

histogramsDefinition:
  - varToPlot: "Raw"

  - varToPlot: "Pmu"
    splitVars: ["", "ReactionCode"]
#    useSampleBinning: true # if not possible, error
    binningFile: "./misc/FHCNumuCC0PiPmuBinning.txt"
    rescaleBinFactor: 100 # / 100 MeV
#    xMax: 2000.
    xTitle: "p_{#mu} (MeV)"
    yTitle: "Counts / 100 MeV"

  - varToPlot: "CosThetamu"
    splitVars: [""]
    useSampleBinning: true
    xTitle: "#{cos}(#{theta}_{#mu})"
#      noData: true
#      binningFile: ""

  - varToPlot: "CosThetamu"
    prefix: "_unNorm"
    splitVars: [ "" ]
    useSampleBinning: true
    rescaleAsBinWidth: false # show the true stat in each bin
    xTitle: "#{cos}(#{theta}_{#mu})"

  # dev Y vs X
  - varToPlot: "CosThetamu:Pmu"
    useSampleBinning: true
    xTitle: "p_{#mu} (MeV)"
    yTitle: "#{cos}(#{theta}_{#mu})"
    zTitle: "Counts (/bin area)"


canvasParameters:
  height: 700
  width: 1200
  nbXplots: 3
  nbYplots: 2

