# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true

  showSelectedEventCount: true

  selectedDataEntry: "Asimov" # default
#  selectedDataEntry: "2p2h twice"
  selectedToyEntry: "Asimov" # default: Asimov
#  selectedToyEntry: "pValueToys" # default: Asimov

  mc:
    tree: "sample_sum"
    nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) )"
#    additionalLeavesStorage: [ "SelectedSample" ]
    filePathList:
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run4aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run5MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run2aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run2wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run3MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run4wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run6MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run7MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run8aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run8wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/run9MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/run4aMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/run5MCsplines.root"

  data:
    - name: "2p2hTwice"
      fromMc: true
      nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) )"

    - name: "RealData"
      nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight"
      filePathList:
        - "./P6T_Latest/Data/run4aMCsplines.root"
        - "./P6T_Latest/Data/run5MCsplines.root"

    - name: "pValueToys"
      fromMc: true
      filePathList:
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run2a_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run3_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run4a_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run4w_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run5_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run6_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run7_throw_splines.root"
#        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run8a_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run8w_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/run9_throw_splines.root"
#        - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded_DetThrows/run4a_throw_splines.root"
#        - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded_DetThrows/run5_throw_splines.root"
      nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) ) * Toy_DetWeight[<I_TOY>]"
      nMaxToys: 2001
      overrideLeafDict: # originalVarName, toyVarName[nMaxToys]
        - { eventVar: "Pmu",            leafVar: "psycheSyst_LeptonMomToy[<I_TOY>]" }
        - { eventVar: "CosThetamu",     leafVar: "psycheSyst_LeptonCosToy[<I_TOY>]" }
        - { eventVar: "SelectedSample", leafVar: "psycheSyst_SelectionToy[<I_TOY>]" }
        - { eventVar: "DetNomWeight",   leafVar: "psycheSyst_WeightToy[<I_TOY>]" }
        - { eventVar: "VertexID",       leafVar: "psycheSyst_iVertexID[<I_TOY>]" }
        - { eventVar: "isRHC",          leafVar: "Run" }
