# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true
  mc:
    tree: "sample_sum"
    nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) ) * passedPsyche"
    filePathList:
      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/run4aMCsplines.root"
      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/run5MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run2aMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run2wMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run3MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run4wMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run6MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run7MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run8aMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run8wMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/run9MCsplines.root"

    toyParameters:
      overrideNominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) ) * Toy_DetWeight[<I_TOY>]"
      nMaxToys: 1000
      overrideVariables: # originalVarName, toyVarName[nMaxToys]
        - { var: "Pmu",            toyVar: "Toy_LeptonMom"}
        - { var: "CosThetamu",     toyVar: "Toy_LeptonCos"}
        - { var: "SelectedSample", toyVar: "Toy_Selection"}
        - { var: "DetNomWeight",   toyVar: "Toy_DetWeight"}
        - { var: "VertexID",       toyVar: "Toy_Selection"}

#  data:
#    tree: "sample_sum"
#    #    nominalWeightFormula: "FluxWeight[0] * DetNomWeight * PileUpWeight * POTWeight * T2KRW_NIWGWeightToy[0]"
#    #    nominalWeightFormula: "FluxWeight[0] * DetNomWeight * PileUpWeight * POTWeight"
#    nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight"
#    filePathList:
#      - "./P6T_Latest/Data/run4aMCsplines.root"
#      - "./P6T_Latest/Data/run5MCsplines.root"
##      - "./P6T_Latest/Data/run2aMCsplines.root"
##      - "./P6T_Latest/Data/run2wMCsplines.root"
##      - "./P6T_Latest/Data/run3MCsplines.root"
##      - "./P6T_Latest/Data/run4wMCsplines.root"
##      - "./P6T_Latest/Data/run6MCsplines.root"
##      - "./P6T_Latest/Data/run7MCsplines.root"
##      - "./P6T_Latest/Data/run8aMCsplines.root"
##      - "./P6T_Latest/Data/run8wMCsplines.root"
##      - "./P6T_Latest/Data/run9MCsplines.root"