# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true

  showSelectedEventCount: true

#  selectedDataEntry: "Asimov" # default
  selectedDataEntry: "P6T"
#  selectedDataEntry: "2p2h twice"
#  selectedToyEntry: "Asimov" # default: Asimov
  selectedToyEntry: "pValueToys" # default: Asimov

  mc:
    tree: "sample_sum"
    selectionCutFormula: "( NVertexID == 1 ) * foundTrueVert * passedPsyche"
    nominalWeightFormula:
      - "FluxWeight[0] * PileUpWeight * POTWeight"
      - "( 1 + ( TMath::Abs(ReactionCode) == 38 ) + ( TMath::Abs(ReactionCode) == 39 ) )"
      - "( DetNomWeight <= 0 ? 0 : ( DetNomWeight >= 10 ? 10 : DetNomWeight ) )"
#    additionalLeavesStorage: [ "SelectedSample" ]
    overrideLeafDict: # originalVarName, otherLeafName[optionalArrayIndex]
      - { eventVar: "Pmu",            leafVar: "PmuCoulombCorrection" } # CC is apply just before the fit in BANFF and MaCh3
    filePathList:
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run4aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run5MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run2aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run2wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run3MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run4wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run6MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run7MCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run8aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run8wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded/WithExtraBranchesForGundam/run9MCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/ExtraBranchesForGundam/run4aMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded/ExtraBranchesForGundam/run5MCsplines.root"

  data:
    - name: "FakeDataStudyTest"
      fromMc: true
      nominalWeightFormula: "FluxWeight[0] * PileUpWeight * POTWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 ) )"

    - name: "P6T"
      tree: "data_event_tree"
      filePathList:
        - "/sps/t2k/common/inputs/OA2020/eventSummary/event_summary_Data.root"
      overrideLeafDict: # originalVarName, otherLeafName[optionalArrayIndex]
        - { eventVar: "Pmu",            leafVar: "RecoMuonMomentum" }
        - { eventVar: "CosThetamu",     leafVar: "RecoMuonCosTheta" }
        - { eventVar: "SelectedSample", leafVar: "SampleID" }

    - name: "pValueToys"
      fromMc: true
      filePathList:
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run2a_throw_splines.root"
#        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run2w_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run3_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run4a_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run4w_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run5_throw_splines.root"
#        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run6_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run7_throw_splines.root"
#        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run8a_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run8w_throw_splines.root"
        - "/sps/t2k/common/inputs/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run9_throw_splines.root"
#        - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run4a_throw_splines.root"
#        - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2020/NDMC_psycheInfoAdded_DetThrows/WithExtraBranchesForGundam/run5_throw_splines.root"
      selectionCutFormula: "( NVertexID == 1 ) * foundTrueVert * passedPsyche"
      nominalWeightFormula:
        - "FluxWeight[0] * PileUpWeight * POTWeight"
        - "( 1 + ( TMath::Abs(ReactionCode) == 38 ) + ( TMath::Abs(ReactionCode) == 39 ) )"
        - "( Toy_DetWeight[<I_TOY>] <= 0 ? 0 : ( Toy_DetWeight[<I_TOY>] >= 10 ? 10 : Toy_DetWeight[<I_TOY>] ) )"
      nMaxToys: 2001
      overrideLeafDict: # originalVarName, toyVarName[nMaxToys]
        - { eventVar: "Pmu",            leafVar: "psycheSyst_LeptonMomToy[<I_TOY>]" }
        - { eventVar: "CosThetamu",     leafVar: "psycheSyst_LeptonCosToy[<I_TOY>]" }
        - { eventVar: "SelectedSample", leafVar: "psycheSyst_SelectionToy[<I_TOY>]" }
        - { eventVar: "DetNomWeight",   leafVar: "psycheSyst_WeightToy[<I_TOY>]" }
